### ISSUE TITLE
CentOS/RHEL 7 reboots fail

### ISSUE THREAD

**Issue by chorankates** [chorankates/rouster#97]
due to changes in version 7, `shutdown -rf now` no longer reboots these machines.

to fix this, need to add `os_version` and take that in to consideration when running OS-specific commands

**Comment by ml-sfdc** [comment]
Here's a possible solution: https://github.com/chorankates/rouster/compare/master...ml-sfdc:master#diff-e279349acfceadf8286b79d987046ad9R665

I was never able to get it to have the same CE6 behavior, so worked around it using a 1m shutdown delay. Not ideal, but it works for now. Another possibility is to set the shutdown time for a specific time, but I've found my VMs have substantial clock skew.

**Comment by chorankates** [comment]
@ml-sfdc i think you're referring to the issue tracked in https://github.com/chorankates/rouster/issues/96. i've got a similar fix in the works, should land tomorrow morning
